// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	audit "github.com/kevin-vargas/logger/audit"
	entities "github.com/kevin-vargas/logger/entities"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
	AuditMsg *audit.Message
	Msg      *entities.Message
}

// Audit provides a mock function with given fields: message
func (_m *Logger) Audit(message *audit.Message) {
	_m.AuditMsg = message
	_m.Called(message)
}

// Debug provides a mock function with given fields: message
func (_m *Logger) Debug(message *entities.Message) {
	_m.Msg = message
	_m.Called(message)
}

// Error provides a mock function with given fields: message
func (_m *Logger) Error(message *entities.Message) {
	_m.Msg = message
	_m.Called(message)
}

// Info provides a mock function with given fields: message
func (_m *Logger) Info(message *entities.Message) {
	_m.Msg = message
	_m.Called(message)
}

// Warn provides a mock function with given fields: message
func (_m *Logger) Warn(message *entities.Message) {
	_m.Msg = message
	_m.Called(message)
}
