// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	zapcore "go.uber.org/zap/zapcore"
)

// BaseEncoder is an autogenerated mock type for the BaseEncoder type
type BaseEncoder struct {
	mock.Mock
}

// AddArray provides a mock function with given fields: key, marshaler
func (_m *BaseEncoder) AddArray(key string, marshaler zapcore.ArrayMarshaler) error {
	ret := _m.Called(key, marshaler)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, zapcore.ArrayMarshaler) error); ok {
		r0 = rf(key, marshaler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddBinary provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddBinary(key string, value []byte) {
	_m.Called(key, value)
}

// AddBool provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddBool(key string, value bool) {
	_m.Called(key, value)
}

// AddByteString provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddByteString(key string, value []byte) {
	_m.Called(key, value)
}

// AddComplex128 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddComplex128(key string, value complex128) {
	_m.Called(key, value)
}

// AddComplex64 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddComplex64(key string, value complex64) {
	_m.Called(key, value)
}

// AddDuration provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddDuration(key string, value time.Duration) {
	_m.Called(key, value)
}

// AddFloat32 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddFloat32(key string, value float32) {
	_m.Called(key, value)
}

// AddFloat64 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddFloat64(key string, value float64) {
	_m.Called(key, value)
}

// AddInt provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddInt(key string, value int) {
	_m.Called(key, value)
}

// AddInt16 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddInt16(key string, value int16) {
	_m.Called(key, value)
}

// AddInt32 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddInt32(key string, value int32) {
	_m.Called(key, value)
}

// AddInt64 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddInt64(key string, value int64) {
	_m.Called(key, value)
}

// AddInt8 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddInt8(key string, value int8) {
	_m.Called(key, value)
}

// AddObject provides a mock function with given fields: key, marshaler
func (_m *BaseEncoder) AddObject(key string, marshaler zapcore.ObjectMarshaler) error {
	ret := _m.Called(key, marshaler)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, zapcore.ObjectMarshaler) error); ok {
		r0 = rf(key, marshaler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddReflected provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddReflected(key string, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddString provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddString(key string, value string) {
	_m.Called(key, value)
}

// AddTime provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddTime(key string, value time.Time) {
	_m.Called(key, value)
}

// AddUint provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUint(key string, value uint) {
	_m.Called(key, value)
}

// AddUint16 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUint16(key string, value uint16) {
	_m.Called(key, value)
}

// AddUint32 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUint32(key string, value uint32) {
	_m.Called(key, value)
}

// AddUint64 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUint64(key string, value uint64) {
	_m.Called(key, value)
}

// AddUint8 provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUint8(key string, value uint8) {
	_m.Called(key, value)
}

// AddUintptr provides a mock function with given fields: key, value
func (_m *BaseEncoder) AddUintptr(key string, value uintptr) {
	_m.Called(key, value)
}

// OpenNamespace provides a mock function with given fields: key
func (_m *BaseEncoder) OpenNamespace(key string) {
	_m.Called(key)
}
