// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zapcore "go.uber.org/zap/zapcore"
)

// ObjectMarshaler is an autogenerated mock type for the ObjectMarshaler type
type ObjectMarshaler struct {
	mock.Mock
}

// MarshalLogObject provides a mock function with given fields: _a0
func (_m *ObjectMarshaler) MarshalLogObject(_a0 zapcore.ObjectEncoder) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(zapcore.ObjectEncoder) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
